### ISSUE TITLE
map + filter + combine operators?

### ISSUE THREAD

**Issue by PhilippMDoerner** [minamorl/rex#2]
Heyho, another neat addition for any kind of observable/subject would be to be able to create new observables via operators.
Like for example I might have a user provide some text-input. If they have typed anything in, I want show some piece of text. If they have not typed anything in, I want to hide some piece of text. 

So effectively, I want to be able to `map` an `Observable<string>` to an `Observable<boolean>`.

Similarly I might want to ignore any text-changes if they only contain whitespaces and thus block an emission from an observable to trigger anything. That would be `filter`-ing events based on an arbitrary callback function I provide. 

Lastly it would be pretty nice if I could `combine` multiple observables if I need data from all of them at the same time, e.g. to validate whether an entire form is filled out correctly by combining observables of all the various input-values from the individual form fields.

That provides pretty much the fundamental building block for anything else you might want to do reactively, which is why I think these 3 are the most important operators to have.

These definitions are straight up lifted from RXJS of course.

**Comment by minamorl** [comment]
It's quite good idea. Pull requests welcome. I think I will add them in future,  but I'm very busy now...

**Comment by PhilippMDoerner** [comment]
All good, first is always staking out whether there even is interest to implement those :smile: 

I'll see if I can come up with anything, because those operators essentially create new observables from old ones, so it's kind of a create operation mangled with more stuff.

**Comment by PhilippMDoerner** [comment]
I have surprised myself and Codium... okay your approach appears to have an absolute ton of merit.

```nim
proc map[T](obs: Observable[T], mapper: proc(value: T): T): Observable[T] =
  ## Create a new Observable by mapping values from the input Observable using `mapper` to a new value
  let result = Observable[T]()
  proc observer(value: T) =
    result.next(mapper(value))
  obs.subscribe(observer)
  return result

proc filter[T](obs: Observable[T], filter: proc(value: T): bool): Observable[T] =
  ## Create a new Observable that returns the value from the input Observable if it passes the filter-criteria aka causes `filter` to return true.
  let result = Observable[T]()
  proc observer(value: T) =
    if filter(value):
      result.next(value)
  obs.subscribe(observer)
  return result

proc tap[T](obs: Observable[T], sideEffect: proc(value: T)): Observable[T] =
  ## Trigger the side-effect in `sideEffect` without changing the original observable
  proc observer(value: T) =
    sideEffect(value)
  obs.subscribe(observer)
  return obs
  ```
  
These were utterly trivial to implement and appear to work as expected. I'll see if I can also get a "combine" operator going to combine arbitrary observables and return their combined values, then I'll look into tests and a PR.

**Comment by PhilippMDoerner** [comment]
Okay, I have a first approach for a `combine` operator:
```nim
proc combine[T, R](
  obs1: Observable[T], 
  obs2: Observable[R]
): Observable[(T, R)] =
  let result = Observable[(T, R)]()
  
  proc obs1Observer(value1: T) =
    result.next((value1, obs2.lastValue))
  obs1.subscribe(obs1Observer)
  
  proc obs2Observer(value2: R) =
    result.next((obs1.lastValue, value2))
  obs2.subscribe(obs2Observer)
  
  return result
  ```

However, what you'd normally want to do is be able to chain *arbitrary* amounts of observables together. I'm not entirely sure how to approach that. That isn't quite feasible this way. In that case I could just write 3 versions of the combine proc, one for 2,3 and 4 different observables and if you want to combine more then you're typically doing something wrong or should combine a subset of those to represent a different concept.

Instead of that I **could** also do it by turning `combine` into a macro and then generating the `combine` proc based on the number of observables as input parameters. But that means including macros into the codebase and those will be harder to reason about, particularly in the medium to long term. 

Any preference on your end whether you'd rather like the minimally limited, but easy to maintain approach (3 combine procs) or the more flexible but *very* hard to maintain approach (macro) @minamorl  ?

**Comment by minamorl** [comment]
How about operator overriding instead of defining macros for chaining?
I''m not sure this idea works tho...
Or I prefer macro way. But sounds a bit overkill.

**Comment by minamorl** [comment]
Anyway your first approach for them are really awesome! I will check it more closely and merge it.
Good job @PhilippMDoerner !

**Comment by PhilippMDoerner** [comment]
> How about operator overriding instead of defining macros for chaining?

That really only means renaming `combine` to `&`. The main problem is the return type. What you'd want when combining tuples is (A, B) & (C) --> (A, B, C). Now figure that out for all possible variations of where you may have any number of types instead of 3 and they may be arbitrarily nested inside the tuple.

There isn't really a neat way to do this without diving into macro territory. 
And if I'm going that route I might as well write the combine macro mentioned earlier, as that would be somewhat simple compared to figuring out arbitrary tuple types on the fly.

It just needs to accept arbitrary numbers of parameters, generate a proc from that with those parameters and copy paste this code block in between the start and end once per observable parameter:
```nim
  proc obs<Num>Observer(value<Num>: R) =
    result.next((<obsNum.lastValue once per each other Observable>, value<Num>))
  obs<Num>.subscribe(obs<Num>Observer)
```

While I can write that, it still comes with a maintenance burden of having to understand that every time. It seems comparatively trivial to just define 3 `combine` procs that accept 2, 3 and 4 Observable-parameters respectively.

**Comment by minamorl** [comment]
@PhilippMDoerner 
Got it. Thanks for clarification. I've tried some macro ways but I couldn't get good result with macros yet.
For maintainability, I would like no-macro way for now. If people gonna like this library and the maintainers come, we can add macros later.

Edit:
I tried `macro combine* (args: varargs[untyped])` way btw

**Comment by PhilippMDoerner** [comment]
Done 

>  I tried macro combine* (args: varargs[untyped]) way btw

Yeah, that'd be the way to go here. You'd need to allow arbitrary amounts of params, then analyze them one by one, extract a sequence of types in string shape and then generate a tuple type for the return type, from there generate the arbitrary amounts of codeblocks in the body etc.

Doable, I just don't find it neat.
