### ISSUE TITLE
Reduce the need for calling `enable`

### ISSUE THREAD

**Issue by PhilippMDoerner** [minamorl/rex#3]
The current usage of `enable` provides somewhat of a limitation.

It basically is just triggering sending all data inside the observable to the subscribers, right? But this now means that I can't add a subscriber after the fact and have them read from the observable-data unless I call enable again, which will also call all the other subscribers. This creates limitations in how I can structure or set up observables, where I can't have an observable that has long-lasting subscribers where new subscribers might arrive at a later time and disappear again (think components that get rendered, during their lifecycle listen to data-changes on the observable and then removed later. Meanwhile another Subscriber might be listening to the observable for the entire duration).

It would thus be beneficial if values would get automatically replayed on subscribe instead of relying on an enable proc to manually do so.

**Comment by minamorl** [comment]
Ya I thought in that way. Since I'm very new to Nim, I have a problem with syncing subscribe variables. If you have a solution let me know!

**Comment by minamorl** [comment]
@PhilippMDoerner Can you check my PR and review it if you are available pls?

**Comment by PhilippMDoerner** [comment]
> Ya I thought in that way. Since I'm very new to Nim, I have a problem with syncing subscribe variables. If you have a solution let me know!

Sadly I don't because that is one of the reasons why, when I tried to initially think this through, it was really damn hard. Your approach was one I had not considered for filling Observables with data, so maybe that is just the way to go.

Gladly will take a look at the PR though!

**Comment by minamorl** [comment]
Since create takes observable as the first argument I removed `enable` now. For the rest part of issues we have discussed about I would like to do it in separate issue. Thank you addressing @PhilippMDoerner !
